### DISCUSSION TITLE
Filter certain persons to add to keywords template on export

### DISCUSSION THREAD

**Discussion by oPromessa** [RhetTbull/osxphotos#1384] [Q&A] [answered]
Quick question...

As I export my Photos library to Synology Photos which does not recognise the RegionName (faces) I'm adding them to keywords with "person:" _prefix_. 

I could use `--person-keyword` and filter `--person` query tag but I'd like to include all pics and add `person:Person1` keywords only for the list of  persons I select, and when they exist.

My `.toml` looks like this but:
* if Person1 or Person2 exists it the exports all persons, say "person:Person1 person:PersonNotToInclude" get included in the keywords list.

```toml
exiftool_merge_keywords = true
exiftool_merge_persons = true
keyword_template = [
    "{var:empty,}{var:name1,Person1}{var:name2,Person2}{person|sort matches {%name1}|{%name2}?person:{person},{%empty}}",
]
```

I guess I must go thru the list of persons and processed them one by one... maybe with the use of an external python function?

**Comment by oPromessa** [comment, marked as answer]
Testing out with the filter example function and **it works!!!** Hopefully will not delay much the export ;)

### TOML file
```toml
exiftool = true
exiftool_merge_keywords = true
exiftool_merge_persons = true
keyword_template = [
    "{person|sort|function:persons.py::myfilter}",
]
```

### Python file:
```python
""" Example of using a custom python function as an osxphotos template filter 

    Use in formath:
    "{template_field|template_filter.py::myfilter}"

    Your filter function will receive a list of strings even if the template renders to a single value.  
    You should expect a list and return a list and be able to handle multi-value templates like {keyword}
    as well as single-value templates like {original_name}
"""
from typing import List

def myfilter(values: List[str]) -> List[str]:
    """Custom filter to add keywords for filtered persons
    filtered_persons = ["Person1", "Person2", "Person3", "Person4"]  # Persons to include in the list

    values = ["person:" + person for person in values if person in filtered_persons]
    
    return values

# Example usage #1:
# input_strings = ["apple", "Person1", "orange", "Person3", "kiwi"]
# result = myfilter(input_strings)
# print(result)

# Example usage #2:
# input_strings = ["apple", "orange", "kiwi"]
# result = myfilter(input_strings)
# print(result)
```
