### DISCUSSION TITLE
Exporting photos using shooting date

### DISCUSSION THREAD

**Discussion by shrekin** [RhetTbull/osxphotos#718] [General]
Hi,

first of all - it's awesome that osxphotos was created.

I'm new to using this tool, and I'm stuck what is the best command line to export all my photos, so I would ask you for advice.
I'd like to export all my photos with all EXIF data, using the original filename and I also want to keep the original shooting date of the file (or replace the current export date/time with the shooting date/time). It would help me to sort files using last modification time column.

Is there any solution for it? :-)

**Comment by RhetTbull** [comment]
Hi. The following command should do what you want with one exception: there is currently no option to export photos using the modification date of the photo. You can use the `--touch-file` option to export photos and set the date of the exported photo to the photo's creation date (what you refer to as "shooting date") but not the modification date.  I also recommend you read the tutorial: `osxphotos tutorial` to get familiar with the tool.

`osxphotos export /path/to/export/folder --exiftool --touch-file`

But you also need to to decide what directory/folder structure you want on export (how do want the photos to be organized). The above command dumps them all in a single folder (/path/to/export/folder) which probably isn't what you really want.  Take a look at the tutorial and the `--export-by-date` and `--directory` options to specify the output folder.  `--export-by-date` sorts them by creation date, e.g. `2020/05/31/photo.jpg`

**Reply by oPromessa** [reply]
My setup, in case it may be helpful:

* Command line:
   * please note I Use the --exportb option as I export the pics into a remote NAS server and keeping the exportdb speeds up the export.
   * then I load up all my options on a `toml` file
```
osxphotos export /Volumes/photo_folder_on_NAS/Pics --exportdb /Users/ABC/Pictures/Logs/.osxphotos_export.db --load-config colibri.toml
```
* contents of colibri.toml
```toml
[export]
cleanup = true
db = "/Users/Shared/Pictures/iPhoto Shared Library.photoslibrary"
description_template = "Album:{album,}{newline}Description:{descr,}"
directory = "{album[/,.|:,.]}"
#dry_run = true
exiftool = true
exiftool_merge_keywords = true
exiftool_merge_persons = true
keyword_template = [ "{keyword}", "{label}", "{searchinfo.activity?activity:{searchinfo.activity},}", "{searchinfo.venue_type?venue_type:{searchinfo.venue_type},}", ]
not_hidden = true
ramdb = true
report = "/Users/ABC/Pictures/Logs/colibri.csv"
retry = 2
skip_bursts = true
skip_live = true
skip_original_if_edited = true
strip = true
timestamp = true
touch_file = true
update = true
verbose = true
```
