### DISCUSSION TITLE
Flow to convert old MPGs in Photos to new MOV

### DISCUSSION THREAD

**Discussion by oPromessa** [RhetTbull/osxphotos#907] [Q&A] [answered]
Hello osxphotos users!

I wanted to convert all my previously loaded MPG old movies on Photos to MOV format. So that I can play with metadata which is not possible on MPG files. 

So I was planning on:

1. List the files: osxphotos query 
2. Convert the files (my files are all referenced) on the file system: ffmpeg
3. Set date/time and gps location related metadata to converted file: exiftool
4. As for keywords. I can assign keywords with exiftool to the file but once imported Photos does not recognize them. And osxphotos import doesn't assign keyword also. I'm trying activescript. Don't know if Python import osxphotos code can help out. 
5. Also have to assign the converted file to the previously assigned album: possibly via python import osxphotos code 
6. And finally delete the .MPG from Photos 

So far I've managed steps 1, 2 and 3. For Steps 4, 5 and 6 any recommendations/comments?

**Comment by RhetTbull** [comment]
Edit: Apparently mpeg doesn't support [metadata](https://exiftool.org/TagNames/MPEG.html) so writing with --exiftool on export won't preserve the keywords. Updated to use a sidecar file to then apply the metadata to the converted .mov file.

Edit 2: fixed sidecar filename

You should be able to do this all with osxphotos. I'd use an actual export to a temp folder instead of a query.  The following commands are from memory so might need some slight tweaking. I suggest reading the [docs](https://rhettbull.github.io/osxphotos/cli.html) to learn what each option does.

1., 2., 3.  `osxphotos export /path/to/export --uti public.mpeg --exiftool --directory "{folder_album}" --sidecar exiftool --post-command exported "ffmpeg --options -i {filepath|shell_quote} {shell_quote,{filepath.parent}/{filepath.stem}.mov}" --post-command "exiftool -overwrite_original -json={shell_quote,{filepath}.json} {shell_quote,{filepath.parent}/{filepath.stem}.mov}" --add-exported-to-album Exported_MPG_movies `
4. 5.  `osxphotos import /path/to/export --glob "*.mov" --exiftool --walk --album "{filepath.parent}" --relative-to "/path/to/export" --split-folder "/"`
6. Go to the Album "Exported_MPG_movies" which will have been created by the first command then delete all the files. (Select then Command + Delete)

I don't use `ffmpeg` so you'll need to adjust the options but using `--post-command` allows you to run a command on the newly exported photo.

**Reply by RhetTbull** [reply]
Not sure what to call it but it might be good to have a new osxphotos command that exports a photo, processes it with user provided command, then reimports it, re-applies all previous metadata and albums, and deletes the original.  This would be useful for this and other use cases like fixing file extensions (#382).

**Reply by RhetTbull** [reply]
This will only work if exiftool can write metadata to MPEG. If it can't (and maybe that's the reason `import` wasn't importing keywords) then this will need some custom python code.

**Comment by RhetTbull** [comment]
Edit: The following will work but it just occurred to me you said your library used referenced files which means this won't work for your specific use case and the converted files would be in the export directory. You'd have to move them to the reference library path before the import. This could be done with another `--post-command exported "mv ..."` command.  Left as an exercise for the reader.

Did some testing. Previous answer is close but unfortunately the exiftool JSON sidecars encode the `SourceFile` field which causes exiftool to reject the metadata when applied to a new source file (`.mov` vs `.mpeg`).  However, looks like we can get around this with XMP sidecar.  The two commands appear to accomplish all your steps with exception of #6 which you can accomplish by selecting all photos in the `Exported_MPG_movies` album.

Create a TOML file called `export_mpg.toml` with these contents (adjust the ffmpeg command as needed)

```toml
[export]
add_exported_to_album = "Exported_MPG_movies"
directory = "{folder_album}"
post_command = [ [ "exported", "ffmpeg -i {filepath|shell_quote} {shell_quote,{filepath.parent}/{filepath.stem}.mov}",], [ "exported", "exiftool -overwrite_original -tagsfromfile {shell_quote,{filepath}.xmp} -all:all {shell_quote,{filepath.parent}/{filepath.stem}.mov}",],]
report = "exported_mpg_files_{today}.csv"
sidecar = [ "xmp",]
uti = "public.mpeg"
verbose = true
timestamp = true
```

Run the following command (substituting your export folder)

`osxphotos export ~/Desktop/export --load-config export_mpg.toml`

Then run the following command to import:

`osxphotos import ~/Desktop/export --glob "*.mov" --exiftool --walk --album "{filepath.parent}" --relative-to ~/Desktop/export --split-folder "/" --verbose --timestamp`

This worked in my limited test. Recommend you try with a test library until you're sure it's working to your liking.

**Reply by RhetTbull** [reply]
note this will also export `.mp4` files which are also mpegs so you may also need to further limit the export criteria if you really only want `.mpg` files.

**Reply by oPromessa** [reply]
Thanks so much. Yes the mpg vs mp4 tag I can filter out. 

Super. Will give it a try later tonight.

**Comment by oPromessa** [comment]
Almost perfect!

Only glitch is that it did not recognise the GPS info on `import` even though it has been included on the file with `exiftool`.
Will do a bit more of testing with more files but wanted you to know the rest is working great!

```sh
$ osxphotos import export --no-progress --verbose --glob "*.mov" --exiftool --walk --album "{filepath.parent}" --relative-to "export" --split-folder "/"
Importing /Users/Shared/Pictures/Export/convert_mpg/export/iPhoto Events/(...)/MOV01046.mov
Imported MOV01046.mov with UUID F48B826F-54AB-4687-8CF2-7D95902CAD16
Setting metadata and location from EXIF for MOV01046.mov
Set metadata for MOV01046.mov:
title='', description='', keywords=['XXXXXXX']
No location to set for MOV01046.mov
Adding photo MOV01046.mov to 1 album
Adding photo MOV01046.mov to album iPhoto Events/(...)
Added MOV01046.mov (F48B826F-54AB-4687-8CF2-7D95902CAD16) to album iPhoto Events/(...)
Done: imported 1 file, 0 errors, 
```

```sh
$ exiftool -G -u -a "/Users/Shared/Pictures/Export/convert_mpg/export/iPhoto Events/(...)/MOV01046.mov" | grep GPS
[XMP]           GPS Latitude                    : XX.633301 N
[XMP]           GPS Longitude                   : YY.900000 W
[Composite]     GPS Latitude Ref                : North
[Composite]     GPS Longitude Ref               : West
[Composite]     GPS Position                    : XX.633301 N, YY.900000 W
```

**Comment by oPromessa** [comment]
Found that on the `import` osxphotos is looking at EXIF:GPSLatitude which is not available on MOV files.

https://github.com/RhetTbull/osxphotos/blob/8caee5a81bfced6a380348e1a9364e39e44ced6a/osxphotos/cli/import_cli.py#L315

What is available is under XMP

```
[XMP]           GPS Latitude                    : XX.633301 N
[XMP]           GPS Longitude                   : YY.900000 W
```

So I'm putting up a code change for: #912 
```python
        if latitude is None:
            latitude = metadata.get("XMP:GPSLatitude"):
        if longitude := metadata.get("EXIF:GPSLongitude"):
            longitude = float(longitude)
            longitude_ref = metadata.get("EXIF:GPSLongitudeRef")
            if longitude_ref == "W":
                longitude = -longitude
            elif longitude_ref != "E":
                longitude = None
        if longitude is None:
            longitude = metadata.get("XMP:GPSLongitude"):
```

**Comment by oPromessa** [comment, marked as answer]
# Convert MPG to MOV | Applicable to other conversions on Photos

## Flow: Find .MPG files (hidden or not hidden) in Photos | export & convert | import | delete
* Export with Keywords and location to XMP sidecar
* Hardlink export option seems to work even with referenced files. Saves some space and disk processing on export by referencing the original files.
   * Maybe on edited files the actual file is exported: skip_original_if_edited = true
* Use ffmpeg to convert MPG to MOV files
* Use exiftool to copy attributes and set all dates including QuickTime:ContentCreateDate
* Set alldates to Original

## Export
* Note: This will include hidden pics, use the `--not-hidden` flag to bypass them or the `--hidden` flag to slect just the hidden pics.
```sh
mkdir export;
osxphotos export export --name MOV02979 --name MOV01046 --name MOV02838 --load-config convert.toml 
 ```

### Auxiliary TOML file
* Please note I use some exiftool related functions (see [my gist on exiftool functions](https://gist.github.com/oPromessa/bf5777d9048a76641fb784eec51d6e3c)) like:
   * `exifcreatedate` to set all dates to the EXIF create date
   * `exifsetMVI` (originally for Canon MVI videos) to make sure all dates (incluing QuickTime are properly set. Applicable to all videos. Does not use Timezone.
```toml
[export]
add_exported_to_album = "Exported_MPG_movies"
directory = "{folder_album}"
query_eval = [ "photo.filename[-3:] == 'MPG'",]
post_command = [ 
# Select one of the following two options for ffmpeg
# ffmpeg standard quality/compression
    [ "exported", "ffmpeg -i {filepath|shell_quote} {shell_quote,{filepath.parent}/{filepath.stem}.MOV}",], 
#  ffmpeg better quality/slower conversion 
#   [ "exported", "ffmpeg -i {filepath|shell_quote} -c:v libx264 -preset veryslow -crf 17 {shell_quote,{filepath.parent}/{filepath.stem}.MOV}",],
    [ "exported", "exiftool -overwrite_original -tagsfromfile {shell_quote,{filepath}.xmp} -all:all {shell_quote,{filepath.parent}/{filepath.stem}.MOV}",],
    [ "exported", "exifcreatedate {shell_quote,{filepath.parent}/{filepath.stem}.MOV}",],
    [ "exported", "exifsetMVI {shell_quote,{filepath.parent}/{filepath.stem}.MOV}",],
]
report = "exported_mpg_files_{today}.csv"
sidecar = [ "xmp",]
uti = "public.mpeg"
skip_original_if_edited = true
verbose = true
timestamp = true
no_progress = true
export_as_hardlink = true
```

## Import
* Note: The hidden pics exported will be imported as *Not Hidden*. You must hide them manually.
 ```sh
osxphotos import export --no-progress --verbose --timestamp --glob "*.MOV" --exiftool --walk --album "{filepath.parent}" --relative-to "export" --split-folder "/" --report "imported_mpg_files_{today}.csv"
```

## Go to album "Exported_MPG_movies"(named above) and delete
* Once you ensure everything's fine...
* Select Command + Right-click to delete
