### ISSUE TITLE
Add --backup export option

### ISSUE THREAD

**Issue by RhetTbull** [RhetTbull/osxphotos#1752]
Add a `--backup` option that exports with all settings needed to easily re-import the library to re-create it. 

`osxphotos export --backup /path/to/backup` would be sufficient to create a full backup with edits, AAE, etc.

See #1751

**Comment by oPromessa** [comment]
Would it also make sense for sync --import to use a database from an export ? Thus avoiding two steps: export and sync --export ?

**Comment by RhetTbull** [comment]
> Would it also make sense for sync --import to use a database from an export ? Thus avoiding two steps: export and sync --export ?

Yes, that would be a good option. I'll open a separate issue. For this issue, I'd also add `osxphotos import --backup` to import from the backup.

**Comment by yatesco** [comment]
hiya - I'm looking for _exactly_ this. I want to treat Photos as a black box and want the security of an independent copy of the (~250GB) database "just in case". I can't simply copy/backup the actual folder because of optimised images, so this looks perfect.

I'll be blunt - having read through the docs and the linked issue I have very little idea of how to achieve this ;-). I simply want a backup for disaster recovery, and whilst this looks like it is more than powerful enough, the cognitive load between a higher level `osxphotos export --backup /path/to/backup` and the current magic incantation is simply too much for a simple brain :-).

What would you suggest a _safe_ starting point set of options would be? 

Thanks!

**Comment by RhetTbull** [comment]
@yatesco The following config file should work. Save the `photos_backup.toml` file to your Pictures folder then you can run osxphotos via:

`osxphotos export /path/to/export --load-config ~/Pictures/photos_backup.toml`

The contents of the TOML file with annotations are:

```toml
[export]
download_missing = true # download missing photos from iCloud, remove if not using iCloud
export_aae = true # export .AAE sidecar files for re-creating edits in Apple Photos
export_by_date = true # export in YYYY/MM/DD/ format
not_shared = true # skip photos in shared albums
preview_if_missing = true # export preview if original is missing
ramdb = true # use in-memory database for faster processing with external disks
sidecar = [ "xmp",] # export sidecar files in XMP format
touch_file = true # touch file to set modify date to photo date
update = true # update the export with any changes made in Photos since the last export
```

[photos_backup.toml.zip](https://github.com/user-attachments/files/18138880/photos_backup.toml.zip)
