### ISSUE TITLE
osxphotos export keeps exporting/updating some unchanged files!

### ISSUE THREAD

**Issue by oPromessa** [RhetTbull/osxphotos#654]
Again, GREEAAATTT JOB!!!!

**Describe the bug**
* While using `--update`, `--cleanup`, `--exiftool`, `--touch-file` options I've noticed that a series of files are always re-exported.
* I though it might have to do with some metadata change from Mac Photos (say faces engine recognition). But I closed down Photos app altogether prior to run `osxphotos` to check.
* I've looked at the `db` and `csv` report file to look for changes on a pic (see analysis below).
* Would welcome any further guidance on troubleshooting!
*  **UPDATE/NOTE 1** About two thirds of the pics seem to be all taken before 1970! Is it something related with epoch??? Still no explanation for the other third, however!
* **UPDATE/NOTE 2** The number of pics re-exported with date taken after 1970 seems to be dropping. Will run one more cycle.

**To Reproduce**
1. What's the full command line you used with osxphotos?
* Command line
```
osxphotos export /Volumes/photo-1/(...) --exportdb ./.osxphotos_export.db --load-config ./colibri.toml
```
* Contents of `colibri.toml`
```toml
[export]
cleanup = true
db = "/Users/Shared/Pictures/iPhoto Shared Library.photoslibrary"
description_template = "Album:{album,}{newline}Description:{descr,}"
directory = "{album[/,.|:,.]}"
#dry_run = true
exiftool = true
exiftool_merge_keywords = true
exiftool_merge_persons = true
keyword_template = [ "{keyword}", "{label}", "{searchinfo.activity?activity:{searchinfo.activity},}", "{searchinfo.venue_type?venue_type:{searchinfo.venue_type},}", ]
not_hidden = true
ramdb = true
report = "/Users/Shared/Pictures/Logs/colibri.csv"
retry = 2
skip_bursts = true
skip_live = true
skip_original_if_edited = true
strip = true
timestamp = true
touch_file = true
update = true
verbose = true
```
2. What was the error output?
* N/A

**Expected behavior**
* Non-changed pics should not be re-exported.

**Analysis**
1. Output of several runs. Total number of pics to export 84818 but then you have around 600-1000 always being updated.
```log
1305963 [notice] --- Start Sun 6 Mar 2022 16:28:00 WET 
2022-03-06 16:28:03.322688 -- osxphotos version 0.47.4
         Exporting 84818 photos to /Volumes/photo-1/(...)...
         Processed: 84818 photos, exported: 1, updated: 989, skipped: 85202, updated EXIF data: 989, missing: 0, error: 0, touched date: 1016
         Elapsed time: 3:31:39
         Deleted: 1 file, 0 directories
1487694 [notice] --- End Sun 6 Mar 2022 20:10:18 WET 
1487695 [notice] --- Start Mon 7 Mar 2022 13:32:00 WET
2022-03-07 13:32:02.412506 -- osxphotos version 0.47.4
         Exporting 84818 photos to /Volumes/photo-1/(...)...
         Processed: 84818 photos, exported: 1, updated: 974, skipped: 85217, updated EXIF data: 974, missing: 0, error: 0, touched date: 1001
         Elapsed time: 3:16:40
         Deleted: 1 file, 0 directories
1669397 [notice] --- End Mon 7 Mar 2022 16:58:17 WET
1669536 [notice] --- Start Mon 7 Mar 2022 21:35:00 WET
2022-03-07 21:35:01.873164 -- osxphotos version 0.47.4
         Exporting 84818 photos to /Volumes/photo-1/(...)...
         Processed: 84818 photos, exported: 1, updated: 696, skipped: 85495, updated EXIF data: 697, missing: 0, error: 0, touched date: 723
         Elapsed time: 3:14:08
         Deleted: 1 file, 0 directories
1850644 [notice] --- End Tue 8 Mar 2022 00:58:02 WET 
```
2. filtering for pic `1969-11-09-1` on the `csv` files from the "last" and the "before last" run produce the same output: exported, updated, exif_updated
```log
2022-03-08 00:21:30.945869 -- Exporting 1969-11-09-1.jpg (1969-11-09-1.jpg) as 1969-11-09-1.jpg (72331/84818)
2022-03-08 00:21:30.982339 -- Writing metadata with exiftool for 1969-11-09-1.jpg
2022-03-08 00:21:31.168031 -- Exported updated file /Volumes/photo-1/(...)/1969-11-09-1.jpg
2022-03-08 00:21:31.168633 -- Touched date on file /Volumes/photo-1/(...)/1969-11-09-1.jpg
```
```sh
$ mlr -C --ojson --icsv grep 1969-11-09-1  colibri.csv
[
{
  "filename": "/Volumes/photo-1/(...)/1969-11-09-1.jpg",
  "exported": 1,
  "new": 0,
  "updated": 1,
  "skipped": 0,
  "exif_updated": 0,
  "touched": 1,
(...)
},
{
  "filename": "/Volumes/photo-1/Family.Photos/1969-01-05 1969-72 Digitalizadas (Album 2)/1969-11-09-1.jpg",
  "exported": 0,
  "new": 0,
  "updated": 0,
  "skipped": 0,
  "exif_updated": 1,
  "touched": 0,
(...)
```
5. Selecting the export_data from `db` I get the same output for bnoth runs.
* 1 = before last run
* 2 = last run
```sql
sqlite> .output 2.export
sqlite> select *  from export_data
   ...> where filepath_normalized like "%1969-11-09-1%";
```
```sh
diff -s 1.export 2.export
Files 1.export and 2.export are identical
```
6. Selecting the photoinfo from the `db` I also get the exact same output for both runs. last and before last. 
```sql
.output 1.phinfo
select photoinfo.*  from export_data, photoinfo
where photoinfo.uuid = export_data.uuid
and filepath_normalized like "%1969-11-09-1%";
```
```
$ cut -f 3 -d "|"  1.phinfo > 1.json
$ cat 1.json
{"albums": ["(...)"], "burst": false, "comments": [], "date": "1969-11-09T13:15:00+01:00", "date_modified": null, "description": null, "exif": {"aperture": null, "bit_rate": null, "camera_make": null, "camera_model": null, "codec": null, "duration": null, "exposure_bias": null, "flash_fired": false, "focal_length": null, "fps": null, "iso": null
(...)
$ diff -s 1.json 2.json
Files 1.json and 2.json are identical
(venv)
$ md5 1.json 2.json
MD5 (1.json) = 47582be389f25116a1b317ddefcca67b
MD5 (2.json) = 47582be389f25116a1b317ddefcca67b
```

**Desktop (please complete the following information):**
 - OS: [e.g. which version of macOS]: `12.2.1`
 - osxphotos version (`osxphotos --version`): `0.47.4`

**Additional context**
