### ISSUE TITLE
Add confirmation before cleanup deletion

### ISSUE THREAD

**Issue by infused-kim** [RhetTbull/osxphotos#733]
Sorry, one more from me :)

**Is your feature request related to a problem? Please describe.**
I ran an export and saw that 133 photos were missing.

So I wanted to run another export just for missing ones to add them to an album with: `osxphotos export icloud_photo_library_export/ --load-config osxphotos.conf --missing --download-missing --add-missing-to-album "osxphotos_missing"`

The app logged:
```
Did not find any photos to export
Cleaning up /Volumes/Photos/icloud_photo_library_export/icloud_photo_library_export
```

And then proceeded to delete for much longer than I would have expected. I assume it started to delete all the photos, since it cleans up anything that was not exported.

It was my mistake to run this command with `cleanup = true`, but it is probably an easy mistake to make for people who use the config option.

**Describe the solution you'd like**
I think the app should say something like "Cleanup will delete XXX (X%) photos. Please confirm whether you would like to proceed [y/N]".

An even better option would be to give the user the option to show which files will be deleted in an fzf style UI, but that's probably quite a bit of effort to implement and perhaps a v2 iteration (if ever).

**Describe alternatives you've considered**
I haven't been able to come up with an alternative, except to be very careful with the arguments.

**Additional context**
My config was:
```toml
[export]
update = true
cleanup = true

report = "photos_export_report.sqlite"
append = true

db = "../Photos.photoslibrary"
tmpdir = "osxphotos_tmp"
directory = "{created.year}/{created.year}-{created.mm}"

theme = "light"
sidecar = [ "xmp",]

person_keyword = true
keyword_template = [
    "Album: {folder_album}",
    "{label}",
    "{favorite?is_favorite}",
    "is_{media_type}",
]
```
